name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci

      - run: npx prisma generate

      - run: npm run electron:build -- --linux
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
          DATABASE_URL: "file:./dev.db"
          NEXT_PUBLIC_QRIS_STRING: ${{ secrets.NEXT_PUBLIC_QRIS_STRING }}

      - uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.AppImage
            dist/latest-linux.yml

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci

      - run: npx prisma generate

      - run: npm run electron:build -- --win
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
          DATABASE_URL: "file:./dev.db"
          NEXT_PUBLIC_QRIS_STRING: ${{ secrets.NEXT_PUBLIC_QRIS_STRING }}

      - uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.exe
            dist/latest.yml
